### ISSUE TITLE
Cannot install `tsdownsample` - NameError build is not defined

### ISSUE THREAD

**Issue by jonasvdd** [predict-idlab/tsdownsample#2]
Hi 👋🏼,

I get the following error when trying to install tsdownsample:

```txt
Collecting tsdownsample
  Downloading tsdownsample-0.1.0a1.tar.gz (5.5 kB)
  Installing build dependencies ...   Getting requirements to build wheel ...   Preparing metadata (pyproject.toml) ... Requirement already satisfied: pandas>=1.3 in /home/jonas/.cache/pypoetry/virtualenvs/semi-guided-speech-27YL4uf1-py3.8/lib/python3.8/site-packages (from tsdownsample) (1.4.0)
Requirement already satisfied: numpy>=1.21 in /home/jonas/.cache/pypoetry/virtualenvs/semi-guided-speech-27YL4uf1-py3.8/lib/python3.8/site-packages (from tsdownsample) (1.22.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/jonas/.cache/pypoetry/virtualenvs/semi-guided-speech-27YL4uf1-py3.8/lib/python3.8/site-packages (from pandas>=1.3->tsdownsample) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/jonas/.cache/pypoetry/virtualenvs/semi-guided-speech-27YL4uf1-py3.8/lib/python3.8/site-packages (from pandas>=1.3->tsdownsample) (2021.3)
Requirement already satisfied: six>=1.5 in /home/jonas/.cache/pypoetry/virtualenvs/semi-guided-speech-27YL4uf1-py3.8/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas>=1.3->tsdownsample) (1.16.0)
Building wheels for collected packages: tsdownsample
  Building wheel for tsdownsample (pyproject.toml) ... error: subprocess-exited-with-error
  
  × Building wheel for tsdownsample (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      A setup.py file already exists. Using it.
      Traceback (most recent call last):
        File "/tmp/pip-install-ptqqurvn/tsdownsample_7026e70fb6cf4d72bd2b00ae792aa535/setup.py", line 28, in <module>
          from setup import *
        File "/tmp/pip-install-ptqqurvn/tsdownsample_7026e70fb6cf4d72bd2b00ae792aa535/setup.py", line 29, in <module>
          build(setup_kwargs)
      NameError: name 'build' is not defined
      Traceback (most recent call last):
        File "/home/jonas/.cache/pypoetry/virtualenvs/semi-guided-speech-27YL4uf1-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/home/jonas/.cache/pypoetry/virtualenvs/semi-guided-speech-27YL4uf1-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/jonas/.cache/pypoetry/virtualenvs/semi-guided-speech-27YL4uf1-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-65vdhqp1/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 56, in build_wheel
          return WheelBuilder.make_in(
        File "/tmp/pip-build-env-65vdhqp1/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 85, in make_in
          wb.build(target_dir=directory)
        File "/tmp/pip-build-env-65vdhqp1/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 118, in build
          self._build(zip_file)
        File "/tmp/pip-build-env-65vdhqp1/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 179, in _build
          self._run_build_command(setup)
        File "/tmp/pip-build-env-65vdhqp1/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 217, in _run_build_command
          subprocess.check_call(
        File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/jonas/.cache/pypoetry/virtualenvs/semi-guided-speech-27YL4uf1-py3.8/bin/python', '/tmp/pip-install-ptqqurvn/tsdownsample_7026e70fb6cf4d72bd2b00ae792aa535/setup.py', 'build', '-b', '/tmp/pip-install-ptqqurvn/tsdownsample_7026e70fb6cf4d72bd2b00ae792aa535/build']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tsdownsample
Failed to build tsdownsample
ERROR: Could not build wheels for tsdownsample, which is required to install pyproject.toml-based projects
```
---

fyi, trying to install it via poetry gives the same error

```
poetry add tsdownsample
Using version ^0.1.0a1 for tsdownsample

Updating dependencies
Resolving dependencies... (5.6s)

Writing lock file

Package operations: 1 install, 2 updates, 0 removals

  • Updating typing-extensions (4.4.0 -> 4.0.1)
  • Updating pydantic (1.10.2 -> 1.8.2)
  • Installing tsdownsample (0.1.0a1): Failed

  CalledProcessError

  Command '['/home/jonas/.cache/pypoetry/virtualenvs/semi-guided-speech-27YL4uf1-py3.8/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/home/jonas/.cache/pypoetry/virtualenvs/semi-guided-speech-27YL4uf1-py3.8', '--no-deps', '/home/jonas/.cache/pypoetry/artifacts/f4/dc/c1/ed26154e04a327d7ece0b3074c32a5b05bf7057f4dd093eb77b29e0b13/tsdownsample-0.1.0a1.tar.gz']' returned non-zero exit status 1.

  at /usr/lib/python3.10/subprocess.py:526 in run
       522│             # We don't call process.wait() as .__exit__ does that for us.
       523│             raise
       524│         retcode = process.poll()
       525│         if check and retcode:
    →  526│             raise CalledProcessError(retcode, process.args,
       527│                                      output=stdout, stderr=stderr)
       528│     return CompletedProcess(process.args, retcode, stdout, stderr)
       529│ 
       530│ 

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/home/jonas/.cache/pypoetry/virtualenvs/semi-guided-speech-27YL4uf1-py3.8/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/home/jonas/.cache/pypoetry/virtualenvs/semi-guided-speech-27YL4uf1-py3.8', '--no-deps', '/home/jonas/.cache/pypoetry/artifacts/f4/dc/c1/ed26154e04a327d7ece0b3074c32a5b05bf7057f4dd093eb77b29e0b13/tsdownsample-0.1.0a1.tar.gz'] errored with the following return code 1, and output: 
  Processing /home/jonas/.cache/pypoetry/artifacts/f4/dc/c1/ed26154e04a327d7ece0b3074c32a5b05bf7057f4dd093eb77b29e0b13/tsdownsample-0.1.0a1.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Building wheels for collected packages: tsdownsample
    Building wheel for tsdownsample (pyproject.toml): started
    Building wheel for tsdownsample (pyproject.toml): finished with status 'error'
    error: subprocess-exited-with-error
    
    × Building wheel for tsdownsample (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [27 lines of output]
        A setup.py file already exists. Using it.
        Traceback (most recent call last):
          File "/tmp/pip-req-build-ubi789br/setup.py", line 28, in <module>
            from setup import *
          File "/tmp/pip-req-build-ubi789br/setup.py", line 29, in <module>
            build(setup_kwargs)
        NameError: name 'build' is not defined
        Traceback (most recent call last):
          File "/home/jonas/.cache/pypoetry/virtualenvs/semi-guided-speech-27YL4uf1-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
            main()
          File "/home/jonas/.cache/pypoetry/virtualenvs/semi-guided-speech-27YL4uf1-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/home/jonas/.cache/pypoetry/virtualenvs/semi-guided-speech-27YL4uf1-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
            return _build_backend().build_wheel(wheel_directory, config_settings,
          File "/tmp/pip-build-env-4xa2n354/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 56, in build_wheel
            return WheelBuilder.make_in(
          File "/tmp/pip-build-env-4xa2n354/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 85, in make_in
            wb.build(target_dir=directory)
          File "/tmp/pip-build-env-4xa2n354/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 118, in build
            self._build(zip_file)
          File "/tmp/pip-build-env-4xa2n354/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 179, in _build
            self._run_build_command(setup)
          File "/tmp/pip-build-env-4xa2n354/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 217, in _run_build_command
            subprocess.check_call(
          File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['/home/jonas/.cache/pypoetry/virtualenvs/semi-guided-speech-27YL4uf1-py3.8/bin/python', '/tmp/pip-req-build-ubi789br/setup.py', 'build', '-b', '/tmp/pip-req-build-ubi789br/build']' returned non-zero exit status 1.
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for tsdownsample
  Failed to build tsdownsample
  ERROR: Could not build wheels for tsdownsample, which is required to install pyproject.toml-based projects
  

  at /usr/lib/python3.10/site-packages/poetry/utils/env.py:1476 in _run
      1472│                 output = subprocess.check_output(
      1473│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1474│                 )
      1475│         except CalledProcessError as e:
    → 1476│             raise EnvCommandError(e, input=input_)
      1477│ 
      1478│         return decode(output)
      1479│ 
      1480│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install /home/jonas/.cache/pypoetry/artifacts/f4/dc/c1/ed26154e04a327d7ece0b3074c32a5b05bf7057f4dd093eb77b29e0b13/tsdownsample-0.1.0a1.tar.gz

  at /usr/lib/python3.10/site-packages/poetry/utils/pip.py:51 in pip_install
       47│ 
       48│     try:
       49│         return environment.run_pip(*args)
       50│     except EnvCommandError as e:
    →  51│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       52│ 

```

**Comment by jvdd** [comment]
Build & release is not stable at all. At the moment I'm working on setting up a CI-CD release matrix that builds cross-environment & cross-Python version! :pray:

**Comment by jvdd** [comment]
Hey @jonasvdd! Normally this should be fixed in the second alpha release (`v0.1.0a2`)
Can you confirm? :)

**Comment by jonasvdd** [comment]
Amazing!! Will test this today!

**Comment by jvdd** [comment]
Does it work? :pray:

**Comment by jonasvdd** [comment]
On my to do list, first 🧯  some 🔥

**Comment by jonasvdd** [comment]
Installation seems to work, but still get this error! ⬇️ 

![image](https://user-images.githubusercontent.com/38005924/204237350-5bc7c7cd-918c-4486-b2db-f08d876aeb16.png)

**Comment by jvdd** [comment]
Glad to see that installation now works! Thx for testing :)

Next on my list is to properly define & test the Python interface for the underlying :crab: code.

I'll close this issue and create a new one concerning the :snake: interface
